### ISSUE TITLE
serializing not working with JSON data Column

### ISSUE THREAD

**Issue by zahessi** [insightindustry/sqlathanor#63]
Hi-hello,
came across a bug that de-serializaition is not supported with JSON type of data column. More specifically, here is my model: 
```

from sqlalchemy import String, Integer, ForeignKey, JSON, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.mysql import TINYINT
from sqlathanor import Column

class Company(Base):
    __tablename__ = "companies"
    __serialization__ = AttributeRels.company_attrs

    name = Column(String(25), nullable=False)
    description = Column(String(140))
    top_manager = Column(Integer, ForeignKey("users.id"))
    invite_link = Column(String(128), default=invite_link_generator)
    style = Column(JSON)
    updated_at = Column(DateTime, default=None, onupdate=datetime.now)

```

The attributes:
```
company_attrs = [
        AttributeConfiguration(name='id', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='name', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='description', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='top_manager', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='invite_link', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='branches', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='style', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='created_at', supports_json=True, supports_dict=True),
        AttributeConfiguration(name='updated_at', supports_json=True, supports_dict=True)
    ]
```

And when I am trying to call instance_of_model.to_dict() the following error occurs:

```
Traceback (most recent call last):
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlathanor/utilities.py", line 180, in get_class_type_key
    class_type_key = class_type.__name__
AttributeError: 'JSON' object has no attribute '__name__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 77, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_JSON'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zahessi/.local/lib/python3.6/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/home/zahessi/.local/lib/python3.6/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/app_steps.py", line 65, in request_with_body
    context.r = _send_request(context, request_verb, url)
  File "features/steps/app_steps.py", line 23, in _send_request
    response = method(url, headers=context.headers)
  File "/home/zahessi/.local/lib/python3.6/site-packages/werkzeug/test.py", line 830, in get
    return self.open(*args, **kw)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/testing.py", line 200, in open
    follow_redirects=follow_redirects
  File "/home/zahessi/.local/lib/python3.6/site-packages/werkzeug/test.py", line 803, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/home/zahessi/.local/lib/python3.6/site-packages/werkzeug/test.py", line 716, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/zahessi/.local/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/home/zahessi/PycharmProjects/eeyore/helper.py", line 46, in decorated
    return f(*args, **kwargs)
  File "/home/zahessi/.local/lib/python3.6/site-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/zahessi/PycharmProjects/eeyore/blueprints/companies/views/company.py", line 35, in get
    return jsonify(company.to_dict())
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlathanor/declarative/_dict_support.py", line 316, in to_dict
    current_nesting = current_nesting)
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlathanor/declarative/_dict_support.py", line 279, in _to_dict
    attribute.name)
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlathanor/declarative/base_model.py", line 155, in _get_serialized_value
    None))
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlathanor/default_serializers.py", line 42, in get_default_serializer
    class_type_key = get_class_type_key(class_attribute, value)
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlathanor/utilities.py", line 182, in get_class_type_key
    class_type_key = str(class_type)
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 589, in __str__
    return str(self.compile())
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 573, in compile
    return dialect.type_compiler.process(self)
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/home/zahessi/.local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 79, in _compiler_dispatch
    raise exc.UnsupportedCompilationError(visitor, cls)
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f5f4f6ac860> can't render element of type <class 'sqlalchemy.sql.sqltypes.JSON'>

```
What is the reason of this: misuse or the bug itself?

**Comment by insightindustry** [comment]
This looks like a bug in SQLAthanor (specifically, SQLAlchemy is raising an `UnsupportedCompilationError` when SQLAthanor is trying to determine the column type name to find a default serializer/deserializer). A fix will be implemented in the next release, which I am hoping to release within a few hours.

**Comment by zahessi** [comment]
Hi-hello, here I am again. is it normal that the json is saved inside the database as a string with escaped double quotes? more specifically, there are rows using the sqlathanor: 
`"{\"primary-color\": \"#232323\", \"secondary-color\": \"#484844\"}"`
and the same request but setting the field of the model manually:
`{"primary-color": "#232323", "secondary-color": "#484844"}`
