### ISSUE TITLE
CannotCoerceError: value (9c9e1c07-5232-496c-a8e0-b412bdcfbd82) was not coerced to a string

### ISSUE THREAD

**Issue by bzaks1424** [insightindustry/sqlathanor#71]
Hey there!

First off - I want to be a long time fan of this. I'm pretty stoked to see this in action.
I think I have something misconfigured here, but I after bumping my head a little - I figured I'd ask here first:

So I have the following table:
```
task_definition_table = Table(
    'task_definition',
    Base.metadata,
    Column(
        'id', UUID(as_uuid=True), primary_key=True, nullable=False,
        default=sqlalchemy.text('uuid_generate_v4()'),
        server_default=sqlalchemy.text('uuid_generate_v4()'),
        supports_json=(False, True)
        # supports_json=True #Also Tried this
    ),
    # Other columns without any support.
   )
```

Which is eventually turned into a class:
```
class Task_Definition(Base):
    def __repr__(self):
        return (
            "<TaskDefinition id='" + str(self.id) + "' "
            + "name='" + self.name + "'>")
    __table__ = task_definition_table
```
I'm I'm getting the following Error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/sqlathanor/declarative/base_model.py", line 175, in _get_serialized_value
    return_value = on_serialize(getattr(self, attribute, None))
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/sqlathanor/default_serializers.py", line 58, in to_str
    allow_empty = True)
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/validator_collection/_decorators.py", line 51, in func_wrapper
    return func(*args, **updated_kwargs)
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/validator_collection/validators.py", line 231, in string
    raise errors.CannotCoerceError('value (%s) was not coerced to a string' % value)
validator_collection.errors.CannotCoerceError: value (9c9e1c07-5232-496c-a8e0-b412bdcfbd82) was not coerced to a string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "db_tester.py", line 21, in <module>
    print(result.to_json())
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/sqlathanor/declarative/_json_support.py", line 83, in to_json
    config_set = config_set)
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/sqlathanor/declarative/_dict_support.py", line 297, in _to_dict
    config_set = config_set)
  File "/mnt/c/Users/me/workspace/odyssey-lib-venv/lib/python3.7/site-packages/sqlathanor/declarative/base_model.py", line 179, in _get_serialized_value
    format)
sqlathanor.errors.ValueSerializationError: attribute 'id' failed serialization to format 'json'
```

Stack:
```
SQLAlchemy (1.3.7)
sqlathanor (0.4.0)
psycopg2 (2.8.3)

$ python3 -V
Python 3.7.3
```

**Comment by insightindustry** [comment]
The issue here is in how SQLAthanor (by default) serializes UUID values. While it tries to serializes them to strings (for JSON), it does not force coercion to string formats by default.

This is actually a bug, because the default serializer *should* coerce values to string. This is just a question of adding the ``coerce_value = True`` argument to the ``to_str()`` default serializer function.

I’ll update that in the next release.

In the meantime, you can apply a workaround by overriding the default serializer function on your ID column. You can do this using ``on_serialize = str`` in your ID column definition.

**Comment by bzaks1424** [comment]
Hey this worked! Thanks!
