### ISSUE TITLE
AttributeError: 'datetime.timedelta' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by bzaks1424** [insightindustry/sqlathanor#73]
Hey There!
I wanted you to know I have a workaround (on_serialize=str), but I figured you'd appreciate me at least giving you a heads up:

So I'm getting the following error:
```
Traceback (most recent call last):
  File "####/lib/python3.7/site-packages/sqlathanor/default_serializers.py", line 67, in to_isoformat
    value = value.isoformat()
AttributeError: 'datetime.timedelta' object has no attribute 'isoformat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "####/lib/python3.7/site-packages/sqlathanor/declarative/base_model.py", line 175, in _get_serialized_value
    return_value = on_serialize(getattr(self, attribute, None))
  File "####/lib/python3.7/site-packages/sqlathanor/default_serializers.py", line 69, in to_isoformat
    raise ValueSerializationError(error.args[0])
sqlathanor.errors.ValueSerializationError: 'datetime.timedelta' object has no attribute 'isoformat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "db_tester.py", line 25, in <module>
    print(thing.to_json(max_nesting=5))
  File "####/lib/python3.7/site-packages/sqlathanor/declarative/_json_support.py", line 83, in to_json
    config_set = config_set)
  File "####/lib/python3.7/site-packages/sqlathanor/declarative/_dict_support.py", line 297, in _to_dict
    config_set = config_set)
  File "####/lib/python3.7/site-packages/sqlathanor/declarative/base_model.py", line 179, in _get_serialized_value
    format)
sqlathanor.errors.ValueSerializationError: attribute 'duration' failed serialization to format 'json'
```

Here is my table:
```
tournament_leaderboard_view = Table(
    'tournament_leaderboard',
    Base.metadata,
    Column('tournament_id', UUID(as_uuid=True), ForeignKey('tournament.id'), primary_key=True, supports_json=True, on_serialize=str),
    Column('team_id', UUID(as_uuid=True), ForeignKey('team.id'), supports_json=True, on_serialize=str),
    Column('display_name', String(length=255), supports_json=True),
    Column('icon', Text, supports_json=True),
    Column('tasks_completed', Integer, supports_json=True),
    Column('duration', Interval, supports_json=True))
```

Here is my class:
```
class Tournament_Leaderboard(Base):
    __table__ = tournament_leaderboard_view
    __serialization__ = [
        AttributeConfiguration(name='total_tasks', supports_json=True)]
    total_tasks = column_property(
        select([func.count(Task.id)])
        .select_from(outerjoin(Task, Round, Task.game_id == Round.game_id))
        .where(
            and_((
                Round.tournament_id
                == tournament_leaderboard_view.c.tournament_id),
                Round.cumulate)
        ).correlate_except(Task)
    )
```

**Comment by insightindustry** [comment]
Hmm - thanks for the heads up! Looks like there's another issue in the default serializer, which should serialize a ``timedelta`` object to an ``int`` with the total number of seconds. I'll fix it in the next release.
